apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: 36620759amara/vets-service
          ports:
            - containerPort: 8083
          resources:
            limits:
              memory: "512Mi"
          env:
          - name: DATABASE_HOST
            value: mysql-customer 
          - name: DATABASE_PORT
            value: "3306"
          - name: DATABASE_NAME
            value: petclinic 
          - name: DATABASE_USER
            value: root 
          - name: DATABASE_PASSWORD
            value: root
          - name: DATABASE_URL
            value: "jdbc:mysql://mysql-customer:3306/petclinic"
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
