apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-keiken-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: keiken.demo.ma
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: customers-service
                port:
                  number: 8081
          - path: /vets
            pathType: Prefix
            backend:
              service:
                name: vets-service
                port:
                  number: 8083